# Generated by Django 2.2.6 on 2019-12-25 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_segment_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
