# Generated by Django 2.2.6 on 2019-12-25 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191225_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsstreet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата затвердження документу'),
        ),
        migrations.AlterField(
            model_name='documentsstreet',
            name='name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictStreetOperations', verbose_name='Назва документу'),
        ),
        migrations.AlterField(
            model_name='documentsstreet',
            name='path_pdf',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шлях до PDF'),
        ),
        migrations.AlterField(
            model_name='documentsstreet',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата додавання документу'),
        ),
    ]
