# Generated by Django 2.2.6 on 2019-12-25 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstreet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата проведення операції над вулицею'),
        ),
    ]
