# Generated by Django 2.2.6 on 2019-12-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191225_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstreet',
            name='document',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.DocumentsStreet'),
        ),
    ]
