# Generated by Django 2.2.6 on 2020-01-06 15:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191230_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=3857),
        ),
    ]
