# Generated by Django 2.2.6 on 2020-02-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_dictbalanceholder'),
        ('main', '0011_auto_20200112_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='geom_type',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='road_destination',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='road_type_significance',
        ),
        migrations.AddField(
            model_name='segment',
            name='balance_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.DictBalanceHolder'),
        ),
        migrations.AddField(
            model_name='segment',
            name='cover_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип покриття'),
        ),
        migrations.AddField(
            model_name='segment',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина дороги(м)'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='road_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Індекс дороги'),
        ),
    ]
