# Generated by Django 3.0.3 on 2020-02-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200202_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsegment',
            name='new',
            field=models.ForeignKey(blank=True, db_column='new', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='main.Segment', verbose_name='Новий сегмент'),
        ),
        migrations.AlterField(
            model_name='operationsegment',
            name='old',
            field=models.ForeignKey(blank=True, db_column='old', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old', to='main.Segment', verbose_name='Старий сегмент'),
        ),
        migrations.AlterField(
            model_name='operationsegmentstreet',
            name='new',
            field=models.ForeignKey(blank=True, db_column='new', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='main.SegmentStreet', verbose_name="Новий зв'язок"),
        ),
        migrations.AlterField(
            model_name='operationsegmentstreet',
            name='old',
            field=models.ForeignKey(blank=True, db_column='old', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old', to='main.SegmentStreet', verbose_name="Старий зв'язок"),
        ),
        migrations.AlterField(
            model_name='operationstreet',
            name='new',
            field=models.ForeignKey(blank=True, db_column='new', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='main.Street', verbose_name='Нова вулиця'),
        ),
        migrations.AlterField(
            model_name='operationstreet',
            name='old',
            field=models.ForeignKey(blank=True, db_column='old', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old', to='main.Street', verbose_name='Стара вулиця'),
        ),
        migrations.AlterField(
            model_name='segmentstreet',
            name='segment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Segment'),
        ),
        migrations.AlterField(
            model_name='segmentstreet',
            name='street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Street'),
        ),
    ]
