# Generated by Django 2.2.6 on 2020-01-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictstreetoperations',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Опис операції'),
        ),
        migrations.AlterField(
            model_name='dictstreetoperations',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва операції'),
        ),
    ]
