# Generated by Django 2.2.6 on 2020-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20200112_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictBalanceHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Назва балансоутримувача')),
            ],
            options={
                'db_table': 'dit_dict_balance_holder',
            },
        ),
    ]
